name: Code Style Check

# Trigger the action on every Pull Request to the main branch
on:
  pull_request:
    branches: [ main, master ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format 14
        run: |
          sudo apt-get update
          # Install version 14 specifically
          sudo apt-get install -y clang-format-14
          # Create a symbolic link so the 'clang-format' command points to version 14
          sudo ln -sf /usr/bin/clang-format-14 /usr/bin/clang-format

      - name: Run clang-format check
        run: |
          # This will print the version in the logs to confirm it matches 14.0.0
          clang-format --version
          
          # Check command
          find . -regex '.*\.\(cpp\|hpp\|h\|cc\|cxx\)' -exec clang-format --dry-run --Werror {} +